name: Destruir Infraestrutura AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  destroy:
    name: Destroy Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        id: init
        working-directory: ./terraform 
        run: terraform init -input=false

      - name: Terraform Refresh
        id: init
        working-directory: ./terraform 
        run: terraform refresh

      - name: Destruir infraestrutura
        working-directory: ./terraform
        run: terraform destroy -auto-approve -input=false
